# .github/workflows/deploy-frontend.yml
name: Deploy Frontend

on:
  push:
    branches: 
      - main
      - 'feature/**'
  # Add manual trigger
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          echo "Starting deployment of ${{ github.ref_name }}..."
          
          # Stop the frontend service
          systemctl stop frontend.service
          
          cd /root/civkit-frontend
          
          # Clear build caches but preserve node_modules
          rm -rf .next
          rm -rf out
          rm -rf .cache
          rm -rf dist
          
          # Clear TypeScript compilation cache
          rm -rf tsconfig.tsbuildinfo
          
          # Stash any changes and checkout main first
          git stash
          git checkout main
          
          # If deploying feature branch
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "Deploying feature branch: ${{ github.ref_name }}"
            git checkout ${{ github.ref_name }}
          fi
          
          git pull origin ${{ github.ref_name }}
          
          # Force clear Next.js cache
          npm run clean || echo "Clean had issues but continuing..."
          
          npm run build || echo "Build had issues but continuing..."
          
          systemctl start frontend.service
          
          echo "Deployment completed!"
