# .github/workflows/deploy-frontend.yml
name: Deploy Frontend

on:
  push:
    branches: 
      - main
      - 'feature/**'
  # Add manual trigger
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          echo "Starting deployment of ${{ github.ref_name }}..."
          
          # Stop the frontend service
          systemctl stop frontend.service
          
          cd /root/civkit-frontend
          
          # Save current changes
          git stash
          
          # Force clean state
          git reset --hard HEAD
          git clean -fd
          
          # Checkout and update main first
          git checkout main
          git pull origin main
          
          # If deploying feature branch
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "Deploying feature branch: ${{ github.ref_name }}"
            git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
            # Force update to match remote
            git reset --hard origin/${{ github.ref_name }}
          fi
          
          # Clear caches but preserve node_modules
          rm -rf .next out .cache dist tsconfig.tsbuildinfo
          
          npm run build || echo "Build had issues but continuing..."
          
          systemctl start frontend.service
          
          echo "Deployment completed!"
