# .github/workflows/deploy.yml
name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          echo "Starting deployment..."
          
          # Stop the frontend service
          echo "Stopping frontend service..."
          systemctl stop frontend.service
          
          cd /root/civkit-frontend
          
          echo "Pulling latest changes..."
          git pull origin main # Will fail if there are issues
          
          echo "Building application..."
          npm run build || echo "Build had issues but continuing..."
          
          # Start service with correct name
          echo "Starting frontend service..."
          systemctl start frontend.service
          
          echo "Deployment completed!"
